apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-sync-hosts
  namespace: cert-manager
data:
  hosts.yaml: |
    hosts:
      - name: homeassistant
        host: 192.168.1.181
        user: nomad
        cert_path: /etc/ssl/int.oquinena.com/tls.crt
        key_path: /etc/ssl/int.oquinena.com/tls.key
        reload_command: "systemctl reload home-assistant@homeassistant || true"
